def printMenu():
    print("Choose your option: \n")
    print("0. Load graph from file.")
    print("1. Number of vertices.")
    print("2. See all vertices.")
    print("3. Verify if there is am edge from x to y.")
    print("4. Print the out degree and the in degree of a vertex.")
    print("5. Modify the cost of an edge.")
    print("6. Add a vertex.")
    print("7. Add an edge.")
    print("8. Remove a vertex.")
    print("9. Remove an edge.")
    print("10. Make a copy of the graph.")
    print("11. Print the vertices and edges of the graph.")
    print("12. Print the copy of the graph with its vertices and edges.")
    print("Type end to exit the program.")